
services:
  - type: web
    name: shark-loterias
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: shark-loterias-db
          property: connectionString

databases:
  - name: shark-loterias-db
    plan: starter
